name: Publish Changes CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: setup stuff
        run: npm run setup
